version: '3.8'

services:
#  nginx:
#    image: nginx:latest
#    ports:
#      - "8010:80"
#    volumes:
#      - .:/src
#      - ./local.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9777:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - '33070:3306'
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:latest

volumes:
  db-data:
